# Generated by Django 3.1 on 2020-08-08 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Barrios',
                'verbose_name_plural': 'Barrioss',
            },
        ),
        migrations.CreateModel(
            name='Capitan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('celular', models.IntegerField(max_length=100)),
            ],
            options={
                'verbose_name': 'Capitan',
                'verbose_name_plural': 'Capitanes',
            },
        ),
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('celular', models.IntegerField(max_length=100)),
                ('capitan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.capitan')),
            ],
            options={
                'verbose_name': 'Lider',
                'verbose_name_plural': 'Lideres',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='PuestosDeVotacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.municipio')),
            ],
            options={
                'verbose_name': 'PuestosDeVotacion',
                'verbose_name_plural': 'PuestosDeVotacions',
            },
        ),
        migrations.CreateModel(
            name='LiderRespBarrio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.barrios')),
                ('capitan_comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.capitan')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.lider')),
            ],
            options={
                'verbose_name': 'liderRespBarrio',
                'verbose_name_plural': 'liderRespBarrios',
            },
        ),
        migrations.CreateModel(
            name='DatosDelVolante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(max_length=100)),
                ('cedula', models.CharField(max_length=100)),
                ('mesa', models.CharField(max_length=100)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.barrios')),
                ('lider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.lider')),
                ('puesto_votacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.puestosdevotacion')),
            ],
            options={
                'verbose_name': 'DatosDelVolante',
                'verbose_name_plural': 'DatosDelVolantes',
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capitanes', models.ManyToManyField(to='polls.Capitan')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.municipio')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.AddField(
            model_name='barrios',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.comuna'),
        ),
    ]
